project_identifier: airbitz
api_key_env: CROWDIN_API_KEY
base_path: ./
files:
  -
    source: '/Localization/relnotes_android.txt'                                    #source files filter
    translation: '/Localization/relnotes_android_%two_letters_code%.txt' #where translations live
  -
    source: '/Localization/store_description_android.txt'                                    #source files filter
    translation: '/Localization/store_description_android_%two_letters_code%.txt' #where translations live
  -
    source: '/Airbitz/airbitz/src/main/res/values/strings.xml'                                    #source files filter
    translation: '/Airbitz/airbitz/src/main/res/values-%two_letters_code%/%original_file_name%' #where translations live
  -
    source: '/Airbitz/airbitz/src/main/res/values/array.xml'                                    #source files filter
    translation: '/Airbitz/airbitz/src/main/res/values-%two_letters_code%/%original_file_name%' #where translations live
